
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

// Tenta carregar dotenv apenas se existir (ambiente local)
try {
  require("dotenv/config");
} catch {
  // dotenv não disponível ou .env não existe - usa variáveis de ambiente do sistema
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Usa process.env diretamente para funcionar com Docker
    url: process.env.DATABASE_URL || "",
  },
});
